version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only:
              - main

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
        # Install dependencies
      - run:
          name: Install Node.js dependencies
          command: npm install

      # Install Truffle globally
      - run:
          name: Install Truffle
          command: npm install -g truffle

      # Execute your tests or Truffle commands
      - run:
          name: Run tests
          command: npm test